[2018-01-09 05:24:47] request.INFO: Matched route "pago_notificacion". {"route_parameters":{"_format":"json","_controller":"AppBundle\\Controller\\PagoController::notificacionAction","_route":"pago_notificacion"},"request_uri":"http://139.59.157.165/pospublicarte/web/pago/notificacion.json"} []
[2018-01-09 05:24:49] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-01-09 05:24:49] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory" at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-01-09 16:04:21] request.INFO: Matched route "cotizacion_new". {"route_parameters":{"_controller":"AppBundle\\Controller\\CotizacionController::newAction","_route":"cotizacion_new"},"request_uri":"http://139.59.157.165/pospublicarte/web/cotizacion/new"} []
[2018-01-09 16:04:21] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-01-09 16:04:21] security.DEBUG: User was reloaded from a user provider. {"username":"publicarteadmin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-01-09 16:04:21] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to AppBundle\Entity\Cotizacion::setSucursal() must be an instance of AppBundle\Entity\Sucursal, null given, called in /var/www/html/pospublicarte/src/AppBundle/Controller/CotizacionController.php on line 123" at /var/www/html/pospublicarte/src/AppBundle/Entity/Cotizacion.php line 303 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to AppBundle\\Entity\\Cotizacion::setSucursal() must be an instance of AppBundle\\Entity\\Sucursal, null given, called in /var/www/html/pospublicarte/src/AppBundle/Controller/CotizacionController.php on line 123 at /var/www/html/pospublicarte/src/AppBundle/Entity/Cotizacion.php:303)"} []
[2018-01-09 16:04:21] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-01-09 16:07:02] request.INFO: Matched route "cotizacion_new". {"route_parameters":{"_controller":"AppBundle\\Controller\\CotizacionController::newAction","_route":"cotizacion_new"},"request_uri":"http://139.59.157.165/pospublicarte/web/cotizacion/new"} []
[2018-01-09 16:07:02] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-01-09 16:07:02] security.DEBUG: User was reloaded from a user provider. {"username":"publicarteadmin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-01-09 16:07:02] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to AppBundle\Entity\Cotizacion::setSucursal() must be an instance of AppBundle\Entity\Sucursal, null given, called in /var/www/html/pospublicarte/src/AppBundle/Controller/CotizacionController.php on line 123" at /var/www/html/pospublicarte/src/AppBundle/Entity/Cotizacion.php line 303 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to AppBundle\\Entity\\Cotizacion::setSucursal() must be an instance of AppBundle\\Entity\\Sucursal, null given, called in /var/www/html/pospublicarte/src/AppBundle/Controller/CotizacionController.php on line 123 at /var/www/html/pospublicarte/src/AppBundle/Entity/Cotizacion.php:303)"} []
[2018-01-09 16:07:02] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-01-09 16:22:41] request.INFO: Matched route "cotizacion_new". {"route_parameters":{"_controller":"AppBundle\\Controller\\CotizacionController::newAction","_route":"cotizacion_new"},"request_uri":"http://139.59.157.165/pospublicarte/web/cotizacion/new"} []
[2018-01-09 16:22:41] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-01-09 16:22:41] security.DEBUG: User was reloaded from a user provider. {"username":"publicarteadmin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-01-09 16:22:41] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to AppBundle\Entity\Cotizacion::setSucursal() must be an instance of AppBundle\Entity\Sucursal, null given, called in /var/www/html/pospublicarte/src/AppBundle/Controller/CotizacionController.php on line 123" at /var/www/html/pospublicarte/src/AppBundle/Entity/Cotizacion.php line 303 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to AppBundle\\Entity\\Cotizacion::setSucursal() must be an instance of AppBundle\\Entity\\Sucursal, null given, called in /var/www/html/pospublicarte/src/AppBundle/Controller/CotizacionController.php on line 123 at /var/www/html/pospublicarte/src/AppBundle/Entity/Cotizacion.php:303)"} []
[2018-01-09 16:22:41] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-01-09 16:33:02] request.INFO: Matched route "orden_new". {"route_parameters":{"_controller":"AppBundle\\Controller\\OrdenController::newAction","_route":"orden_new"},"request_uri":"http://139.59.157.165/pospublicarte/web/orden/new"} []
[2018-01-09 16:33:02] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-01-09 16:33:02] security.DEBUG: User was reloaded from a user provider. {"username":"publicarteadmin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-01-09 16:33:02] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to AppBundle\Entity\Orden::setSucursal() must be an instance of AppBundle\Entity\Sucursal, null given, called in /var/www/html/pospublicarte/src/AppBundle/Controller/OrdenController.php on line 191" at /var/www/html/pospublicarte/src/AppBundle/Entity/Orden.php line 364 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to AppBundle\\Entity\\Orden::setSucursal() must be an instance of AppBundle\\Entity\\Sucursal, null given, called in /var/www/html/pospublicarte/src/AppBundle/Controller/OrdenController.php on line 191 at /var/www/html/pospublicarte/src/AppBundle/Entity/Orden.php:364)"} []
[2018-01-09 16:33:02] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-01-09 22:36:37] request.INFO: Matched route "orden_new". {"route_parameters":{"_controller":"AppBundle\\Controller\\OrdenController::newAction","_route":"orden_new"},"request_uri":"http://139.59.157.165/pospublicarte/web/orden/new"} []
[2018-01-09 22:36:37] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-01-09 22:36:37] security.DEBUG: User was reloaded from a user provider. {"username":"publicarteadmin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-01-09 22:36:37] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to AppBundle\Entity\Orden::setSucursal() must be an instance of AppBundle\Entity\Sucursal, null given, called in /var/www/html/pospublicarte/src/AppBundle/Controller/OrdenController.php on line 191" at /var/www/html/pospublicarte/src/AppBundle/Entity/Orden.php line 364 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to AppBundle\\Entity\\Orden::setSucursal() must be an instance of AppBundle\\Entity\\Sucursal, null given, called in /var/www/html/pospublicarte/src/AppBundle/Controller/OrdenController.php on line 191 at /var/www/html/pospublicarte/src/AppBundle/Entity/Orden.php:364)"} []
[2018-01-09 22:36:37] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-01-09 22:43:35] request.INFO: Matched route "pago_notificacion". {"route_parameters":{"_format":"json","_controller":"AppBundle\\Controller\\PagoController::notificacionAction","_route":"pago_notificacion"},"request_uri":"http://139.59.157.165/pospublicarte/web/pago/notificacion.json"} []
[2018-01-09 22:43:35] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-01-09 22:43:35] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory" at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-01-10 01:39:01] request.INFO: Matched route "pago_notificacion". {"route_parameters":{"_format":"json","_controller":"AppBundle\\Controller\\PagoController::notificacionAction","_route":"pago_notificacion"},"request_uri":"http://139.59.157.165/pospublicarte/web/pago/notificacion.json"} []
[2018-01-10 01:39:01] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-01-10 01:39:01] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory" at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-01-10 01:49:47] request.INFO: Matched route "pago_notificacion". {"route_parameters":{"_format":"json","_controller":"AppBundle\\Controller\\PagoController::notificacionAction","_route":"pago_notificacion"},"request_uri":"http://139.59.157.165/pospublicarte/web/pago/notificacion.json"} []
[2018-01-10 01:49:47] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-01-10 01:49:47] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory" at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-01-10 06:07:18] request.INFO: Matched route "pago_notificacion". {"route_parameters":{"_format":"json","_controller":"AppBundle\\Controller\\PagoController::notificacionAction","_route":"pago_notificacion"},"request_uri":"http://139.59.157.165/pospublicarte/web/pago/notificacion.json"} []
[2018-01-10 06:07:18] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-01-10 06:07:18] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory" at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-01-10 06:07:49] request.INFO: Matched route "orden_index". {"route_parameters":{"_controller":"AppBundle\\Controller\\OrdenController::indexAction","_route":"orden_index"},"request_uri":"http://139.59.157.165/pospublicarte/web/orden/"} []
[2018-01-10 06:07:49] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-01-10 06:07:49] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-01-10 06:07:49] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT o0_.id AS id0, o0_.foliofactura AS foliofactura1, o0_.subtotal AS subtotal2, o0_.iva AS iva3, o0_.total AS total4, o0_.motivocancelacion AS motivocancelacion5, o0_.fecha AS fecha6, o0_.fechaentrega AS fechaentrega7, o0_.fecharecepcion AS fecharecepcion8, o0_.block AS block9, o0_.original AS original10, o0_.colorcopias AS colorcopias11, o0_.medidaimpresion AS medidaimpresion12, o0_.papel AS papel13, o0_.folio AS folio14, o0_.observaciones AS observaciones15, o0_.especial AS especial16, o0_.activo AS activo17, o0_.id_cotizacion AS id_cotizacion18, o0_.id_usuario AS id_usuario19, o0_.id_empresa AS id_empresa20, o0_.id_sucursal AS id_sucursal21, o0_.id_seccion AS id_seccion22, o0_.id_cliente AS id_cliente23, o0_.id_contacto AS id_contacto24, o0_.id_moneda AS id_moneda25, o0_.id_ordenestado AS id_ordenestado26, o0_.id_usocfdi AS id_usocfdi27, o0_.id_metodopago AS id_metodopago28, o0_.id_mediopago AS id_mediopago29 FROM orden o0_ INNER JOIN ordenestado o1_ ON o0_.id_ordenestado = o1_.id WHERE o1_.id = 1 OR o1_.id = 2':  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'o0_.folio' in 'field list'" at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT o0_.id AS id0, o0_.foliofactura AS foliofactura1, o0_.subtotal AS subtotal2, o0_.iva AS iva3, o0_.total AS total4, o0_.motivocancelacion AS motivocancelacion5, o0_.fecha AS fecha6, o0_.fechaentrega AS fechaentrega7, o0_.fecharecepcion AS fecharecepcion8, o0_.block AS block9, o0_.original AS original10, o0_.colorcopias AS colorcopias11, o0_.medidaimpresion AS medidaimpresion12, o0_.papel AS papel13, o0_.folio AS folio14, o0_.observaciones AS observaciones15, o0_.especial AS especial16, o0_.activo AS activo17, o0_.id_cotizacion AS id_cotizacion18, o0_.id_usuario AS id_usuario19, o0_.id_empresa AS id_empresa20, o0_.id_sucursal AS id_sucursal21, o0_.id_seccion AS id_seccion22, o0_.id_cliente AS id_cliente23, o0_.id_contacto AS id_contacto24, o0_.id_moneda AS id_moneda25, o0_.id_ordenestado AS id_ordenestado26, o0_.id_usocfdi AS id_usocfdi27, o0_.id_metodopago AS id_metodopago28, o0_.id_mediopago AS id_mediopago29 FROM orden o0_ INNER JOIN ordenestado o1_ ON o0_.id_ordenestado = o1_.id WHERE o1_.id = 1 OR o1_.id = 2':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'o0_.folio' in 'field list' at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'o0_.folio' in 'field list' at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'o0_.folio' in 'field list' at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []
[2018-01-10 06:07:49] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-01-10 06:07:49] request.INFO: Matched route "orden_index". {"route_parameters":{"_controller":"AppBundle\\Controller\\OrdenController::indexAction","_route":"orden_index"},"request_uri":"http://139.59.157.165/pospublicarte/web/orden/"} []
[2018-01-10 06:07:49] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-01-10 06:07:49] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-01-10 06:07:49] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT o0_.id AS id0, o0_.foliofactura AS foliofactura1, o0_.subtotal AS subtotal2, o0_.iva AS iva3, o0_.total AS total4, o0_.motivocancelacion AS motivocancelacion5, o0_.fecha AS fecha6, o0_.fechaentrega AS fechaentrega7, o0_.fecharecepcion AS fecharecepcion8, o0_.block AS block9, o0_.original AS original10, o0_.colorcopias AS colorcopias11, o0_.medidaimpresion AS medidaimpresion12, o0_.papel AS papel13, o0_.folio AS folio14, o0_.observaciones AS observaciones15, o0_.especial AS especial16, o0_.activo AS activo17, o0_.id_cotizacion AS id_cotizacion18, o0_.id_usuario AS id_usuario19, o0_.id_empresa AS id_empresa20, o0_.id_sucursal AS id_sucursal21, o0_.id_seccion AS id_seccion22, o0_.id_cliente AS id_cliente23, o0_.id_contacto AS id_contacto24, o0_.id_moneda AS id_moneda25, o0_.id_ordenestado AS id_ordenestado26, o0_.id_usocfdi AS id_usocfdi27, o0_.id_metodopago AS id_metodopago28, o0_.id_mediopago AS id_mediopago29 FROM orden o0_ INNER JOIN ordenestado o1_ ON o0_.id_ordenestado = o1_.id WHERE o1_.id = 1 OR o1_.id = 2':  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'o0_.folio' in 'field list'" at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT o0_.id AS id0, o0_.foliofactura AS foliofactura1, o0_.subtotal AS subtotal2, o0_.iva AS iva3, o0_.total AS total4, o0_.motivocancelacion AS motivocancelacion5, o0_.fecha AS fecha6, o0_.fechaentrega AS fechaentrega7, o0_.fecharecepcion AS fecharecepcion8, o0_.block AS block9, o0_.original AS original10, o0_.colorcopias AS colorcopias11, o0_.medidaimpresion AS medidaimpresion12, o0_.papel AS papel13, o0_.folio AS folio14, o0_.observaciones AS observaciones15, o0_.especial AS especial16, o0_.activo AS activo17, o0_.id_cotizacion AS id_cotizacion18, o0_.id_usuario AS id_usuario19, o0_.id_empresa AS id_empresa20, o0_.id_sucursal AS id_sucursal21, o0_.id_seccion AS id_seccion22, o0_.id_cliente AS id_cliente23, o0_.id_contacto AS id_contacto24, o0_.id_moneda AS id_moneda25, o0_.id_ordenestado AS id_ordenestado26, o0_.id_usocfdi AS id_usocfdi27, o0_.id_metodopago AS id_metodopago28, o0_.id_mediopago AS id_mediopago29 FROM orden o0_ INNER JOIN ordenestado o1_ ON o0_.id_ordenestado = o1_.id WHERE o1_.id = 1 OR o1_.id = 2':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'o0_.folio' in 'field list' at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'o0_.folio' in 'field list' at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'o0_.folio' in 'field list' at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []
[2018-01-10 06:07:49] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-01-10 06:07:49] request.INFO: Matched route "orden_index". {"route_parameters":{"_controller":"AppBundle\\Controller\\OrdenController::indexAction","_route":"orden_index"},"request_uri":"http://139.59.157.165/pospublicarte/web/orden/"} []
[2018-01-10 06:07:49] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-01-10 06:07:49] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-01-10 06:07:49] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT o0_.id AS id0, o0_.foliofactura AS foliofactura1, o0_.subtotal AS subtotal2, o0_.iva AS iva3, o0_.total AS total4, o0_.motivocancelacion AS motivocancelacion5, o0_.fecha AS fecha6, o0_.fechaentrega AS fechaentrega7, o0_.fecharecepcion AS fecharecepcion8, o0_.block AS block9, o0_.original AS original10, o0_.colorcopias AS colorcopias11, o0_.medidaimpresion AS medidaimpresion12, o0_.papel AS papel13, o0_.folio AS folio14, o0_.observaciones AS observaciones15, o0_.especial AS especial16, o0_.activo AS activo17, o0_.id_cotizacion AS id_cotizacion18, o0_.id_usuario AS id_usuario19, o0_.id_empresa AS id_empresa20, o0_.id_sucursal AS id_sucursal21, o0_.id_seccion AS id_seccion22, o0_.id_cliente AS id_cliente23, o0_.id_contacto AS id_contacto24, o0_.id_moneda AS id_moneda25, o0_.id_ordenestado AS id_ordenestado26, o0_.id_usocfdi AS id_usocfdi27, o0_.id_metodopago AS id_metodopago28, o0_.id_mediopago AS id_mediopago29 FROM orden o0_ INNER JOIN ordenestado o1_ ON o0_.id_ordenestado = o1_.id WHERE o1_.id = 1 OR o1_.id = 2':  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'o0_.folio' in 'field list'" at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT o0_.id AS id0, o0_.foliofactura AS foliofactura1, o0_.subtotal AS subtotal2, o0_.iva AS iva3, o0_.total AS total4, o0_.motivocancelacion AS motivocancelacion5, o0_.fecha AS fecha6, o0_.fechaentrega AS fechaentrega7, o0_.fecharecepcion AS fecharecepcion8, o0_.block AS block9, o0_.original AS original10, o0_.colorcopias AS colorcopias11, o0_.medidaimpresion AS medidaimpresion12, o0_.papel AS papel13, o0_.folio AS folio14, o0_.observaciones AS observaciones15, o0_.especial AS especial16, o0_.activo AS activo17, o0_.id_cotizacion AS id_cotizacion18, o0_.id_usuario AS id_usuario19, o0_.id_empresa AS id_empresa20, o0_.id_sucursal AS id_sucursal21, o0_.id_seccion AS id_seccion22, o0_.id_cliente AS id_cliente23, o0_.id_contacto AS id_contacto24, o0_.id_moneda AS id_moneda25, o0_.id_ordenestado AS id_ordenestado26, o0_.id_usocfdi AS id_usocfdi27, o0_.id_metodopago AS id_metodopago28, o0_.id_mediopago AS id_mediopago29 FROM orden o0_ INNER JOIN ordenestado o1_ ON o0_.id_ordenestado = o1_.id WHERE o1_.id = 1 OR o1_.id = 2':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'o0_.folio' in 'field list' at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'o0_.folio' in 'field list' at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'o0_.folio' in 'field list' at /var/www/html/pospublicarte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []
[2018-01-10 06:07:49] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-01-10 06:42:01] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /images/ecdc128.jpg" (from "http://139.59.157.165/pospublicarte/web/cotizacion/showprint/6")" at /var/www/html/pospublicarte/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /images/ecdc128.jpg\" (from \"http://139.59.157.165/pospublicarte/web/cotizacion/showprint/6\") at /var/www/html/pospublicarte/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/pospublicarte/app/cache/prod/appProdProjectContainerUrlMatcher.php:1887)"} []
[2018-01-10 06:42:08] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /images/ecdc128.jpg" (from "http://139.59.157.165/pospublicarte/web/cotizacion/showprint/6")" at /var/www/html/pospublicarte/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /images/ecdc128.jpg\" (from \"http://139.59.157.165/pospublicarte/web/cotizacion/showprint/6\") at /var/www/html/pospublicarte/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/pospublicarte/app/cache/prod/appProdProjectContainerUrlMatcher.php:1887)"} []
[2018-01-10 16:12:55] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /js/material.min.js.map" (from "http://139.59.157.165/pospublicarte/web/panelcotizacion/")" at /var/www/html/pospublicarte/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /js/material.min.js.map\" (from \"http://139.59.157.165/pospublicarte/web/panelcotizacion/\") at /var/www/html/pospublicarte/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/pospublicarte/app/cache/prod/appProdProjectContainerUrlMatcher.php:1887)"} []
